---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.appDefaultPort }}